name: Fetch Valencia time

on:
  schedule:
    - cron: '*/60 * * * *'  # Run every minute

permissions:
  contents: write

jobs:
  update-time:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pillow

    - name: Run script
      run: python script.py  # Replace with your script's filename

    - name: Commit and push if changed
      run: |
        git diff
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git commit -am "Fetch Valencia time" || exit 0
        git push